Repository astriv-solutions/flaire-web, pull requests merged in 2025-05, with the labels that each got.

#2 fix: Initial style updates
  src/app/globals.css
  src/components/Benefits/Benefits.tsx
  src/components/CTA.tsx
  src/components/FAQ.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Hero.tsx
  src/components/Pricing/PricingColumn.tsx
  src/components/Section.tsx
  src/components/Testimonials.tsx
Labels: style

#3 style: Style updates
  src/app/globals.css
  src/components/Footer.tsx
Labels: style

#6 refactor: Initial content update
  src/components/FAQ.tsx
  src/components/Footer.tsx
  src/components/Hero.tsx
  src/data/benefits.tsx
  src/data/cta.ts
  src/data/faq.ts
  src/data/footer.ts
  src/data/hero.ts
  src/data/pricing.ts
  src/types.ts
  src/utils.tsx
Labels: bug, documentation

#15 Branch update
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Benefits/BenefitSection.tsx
  src/components/CountUp.tsx
  src/components/CursorDot.tsx
  src/components/FlowingMenu.tsx
  src/components/Header.tsx
  src/components/Hero.tsx
  src/components/InfiniteMenu.tsx
  src/components/Logos.tsx
  src/components/Magnet.tsx
  src/components/PixelCard.tsx
  src/components/Pricing/Pricing.tsx
  src/components/Pricing/PricingColumn.tsx
  src/components/Stats.tsx
  src/components/Testimonials.tsx
  src/components/TiltedCard.tsx
  src/data/flowingmenu.ts
  src/data/hero.ts
  src/data/pricing.ts
  src/data/stats.tsx
  src/data/testimonials.ts
  src/lib/utils.ts
  src/types.ts
  tailwind.config.ts
Labels: documentation

#16 Merge pull request #15 from astriv-solutions/deployment
  README.md
  public/images/testimonial-1.webp
  public/images/testimonial-2.webp
  public/images/testimonial-3.webp
  src/app/page.tsx
  src/data/footer.ts
  src/data/hero.ts
  src/data/testimonials.ts
Labels: documentation

#26 Merge pull request #21 from astriv-solutions/deployment
  .gitignore
  package-lock.json
  package.json
  src/components/CTA.tsx
  src/components/Header.tsx
  src/data/menuItems.ts
  src/types.ts
Labels: enhancement, style
